angular:
  image: httpd
  ports:
    - "9999:80"
  links:
    - node
  volumes:
    - ./frontend/dist:/usr/local/apache2/htdocs/
node:
    build: .
    command: "npm start"
    ports:
        - "5000:80"
    links:
        - mongo
    environment:
        PORT: 27017
    # volumes:
    #     - ./backend:/usr/src/app
mongo:
    image: mongo:latest
    volumes:
        - ./database:/kmer-database
        - ./scripts:/src
        - /data/docker:/data/db
